# Generated by Django 6.1 on 2026-08-22 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('parcels', '0002_alter_customerparcel_api_sp_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(blank=True, editable=False, max_length=50)),
                ('status', models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid')], default='Unpaid', max_length=10)),
                ('date', models.DateField(auto_now_add=True)),
                ('account_name', models.CharField(choices=[('Via Bank', 'Via Bank'), ('EasyPaisa', 'EasyPaisa'), ('JazzCash', 'JazzCash'), ('Cash', 'Cash')], default='Via Bank', max_length=20)),
                ('cod', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('flyer_charges', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_tax', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('delivery_charges', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('parcel_from', models.CharField(blank=True, max_length=100, null=True)),
                ('parcel_to', models.CharField(blank=True, max_length=100, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='customers.customer')),
                ('parcels', models.ManyToManyField(blank=True, related_name='invoices', to='parcels.customerparcel')),
            ],
        ),
    ]
