# Generated by Django 6.1 on 2026-08-19 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerParcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cn', models.CharField(blank=True, editable=False, max_length=50)),
                ('destination', models.CharField(blank=True, max_length=100, null=True)),
                ('delivery_rider_service_provider', models.CharField(blank=True, max_length=100, null=True)),
                ('api_sp_type', models.CharField(default='OVERNIGHT', max_length=50)),
                ('api_tracking_no', models.CharField(blank=True, max_length=100, null=True)),
                ('tpl_payment_status', models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid')], default='Unpaid', max_length=10)),
                ('consignee', models.CharField(blank=True, max_length=255, null=True)),
                ('consignee_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('alternate_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('order_number', models.CharField(blank=True, max_length=100, null=True)),
                ('issue_destination', models.CharField(blank=True, max_length=100, null=True)),
                ('cod', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('rts_cod', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('parcel_declared_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('service_type', models.CharField(default='COD', max_length=50)),
                ('parcel_weight', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('third_party_weight', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('number_of_pieces', models.PositiveIntegerField(default=1)),
                ('replace', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3)),
                ('product', models.TextField(blank=True, default='No', null=True)),
                ('instructions', models.TextField(blank=True, default='Handle with Care', null=True)),
                ('flyer_size', models.CharField(blank=True, max_length=50, null=True)),
                ('flyer_qty', models.PositiveIntegerField(default=0)),
                ('address', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('shipper_advice_remark', models.TextField(blank=True, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('active', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=3)),
                ('status', models.CharField(choices=[('Order', 'Order'), ('Picked', 'Picked'), ('In Transit', 'In Transit'), ('Delivered', 'Delivered'), ('Parcel Not Available', 'Parcel Not Available'), ('Returned', 'Returned')], default='Order', max_length=30)),
                ('reason', models.CharField(blank=True, max_length=100, null=True)),
                ('proof_image', models.ImageField(blank=True, null=True, upload_to='proof_images/')),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('delivery_time', models.TimeField(blank=True, null=True)),
                ('share', models.CharField(choices=[('No Share', 'No Share')], default='No Share', max_length=50)),
                ('order_from', models.CharField(blank=True, max_length=100, null=True)),
                ('store_order_number', models.CharField(blank=True, max_length=100, null=True)),
                ('loadsheet', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_loadsheet', models.CharField(blank=True, max_length=100, null=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('shipment_date', models.DateTimeField(blank=True, null=True)),
                ('branch', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.CharField(blank=True, max_length=100, null=True)),
                ('rate_calculation_mode', models.CharField(choices=[('Automatic', 'Automatic'), ('Manual', 'Manual')], default='Automatic', max_length=20)),
                ('total_gst', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_feul_tax', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_return', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('flyer_charges', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('third_party_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tpl_net_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('delivery_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('net_total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('qr_code_upload', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('bar_code_upload', models.ImageField(blank=True, null=True, upload_to='bar_codes/')),
                ('pl_qr_code_upload', models.ImageField(blank=True, null=True, upload_to='pl_qr_codes/')),
                ('pl_bar_code_upload', models.ImageField(blank=True, null=True, upload_to='pl_bar_codes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shipper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcels', to='customers.customer')),
            ],
        ),
    ]
