# Generated by Django 6.1 on 2026-08-19 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerparcel',
            name='api_sp_type',
            field=models.CharField(choices=[('PostEx Normal', 'PostEx Normal'), ('PostEx Reversed', 'PostEx Reversed'), ('PostEx Replacement', 'PostEx Replacement'), ('Rush Trax', 'Rush Trax'), ('Trax Swift', 'Trax Swift'), ('Trax Saver plus', 'Trax Saver plus'), ('Trax Same day', 'Trax Same day'), ('Orio COD', 'Orio COD'), ('Digi detain', 'Digi detain'), ('Digi overnight', 'Digi overnight'), ('Digi overland', 'Digi overland'), ('Rocket LEO', 'Rocket LEO'), ('Rocket LEO - Detain', 'Rocket LEO - Detain'), ('Rocket LEO - Overland', 'Rocket LEO - Overland'), ('Rocket POSTEX', 'Rocket POSTEX'), ('Rocket TRAX', 'Rocket TRAX'), ('Rocket TRAX - Detain', 'Rocket TRAX - Detain'), ('Rocket', 'Rocket'), ('Rocket Detain', 'Rocket Detain'), ('Rocket Overland', 'Rocket Overland'), ('IEPS COD', 'IEPS COD'), ('IEPS Non COD', 'IEPS Non COD'), ('IEPS Detain', 'IEPS Detain'), ('IEPS Overland (Non COD)', 'IEPS Overland (Non COD)'), ('IEPS overland COD', 'IEPS overland COD'), ('IEPS Bulk', 'IEPS Bulk'), ('M&P Overnight', 'M&P Overnight'), ('M&P Second Day', 'M&P Second Day'), ('TCS Express', 'TCS Express'), ('TCS Economy Express', 'TCS Economy Express'), ('TCS MYO (SELF COLLECTION)', 'TCS MYO (SELF COLLECTION)'), ('LEOPARD DETAIN', 'LEOPARD DETAIN'), ('LEOPARD OVERLAND', 'LEOPARD OVERLAND'), ('LEOPARD OVERNIGHT', 'LEOPARD OVERNIGHT'), ('BLUE CARGO (BG)', 'BLUE CARGO (BG)'), ('BLUE TRUNK (BT)', 'BLUE TRUNK (BT)'), ('BLUE EDGE (BE)', 'BLUE EDGE (BE)'), ('Heavy Shipment', 'Heavy Shipment'), ('Normal', 'Normal'), ('Rush Trax | overnight (Digi) | Orio COD', 'Rush Trax | overnight (Digi) | Orio COD'), ('Saver plus Trax | detain (Digi)', 'Saver plus Trax | detain (Digi)'), ('Swift Trax | overland (Digi)', 'Swift Trax | overland (Digi)'), ('Same day Trax', 'Same day Trax'), ('COD', 'COD'), ('Non COD', 'Non COD'), ('Detain', 'Detain'), ('Overland (Non COD)', 'Overland (Non COD)'), ('overland COD', 'overland COD'), ('Bulk', 'Bulk'), ('Overnight M&P', 'Overnight M&P'), ('Second Day M&P', 'Second Day M&P'), ('Express', 'Express'), ('Economy Express', 'Economy Express'), ('MYO (SELF COLLECTION)', 'MYO (SELF COLLECTION)'), ('OVERLAND', 'OVERLAND'), ('OVERNIGHT', 'OVERNIGHT'), ('Reversed (PostEx)', 'Reversed (PostEx)'), ('Replacement (PostEx)', 'Replacement (PostEx)')], default='OVERNIGHT', max_length=100),
        ),
    ]
