# Generated by Django 6.1 on 2026-08-22 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0002_alter_customerparcel_api_sp_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusNarration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Order', 'Order'), ('Picked', 'Picked'), ('In Transit', 'In Transit'), ('Delivered', 'Delivered'), ('Parcel Not Available', 'Parcel Not Available'), ('Returned', 'Returned')], max_length=30, unique=True)),
                ('narration', models.TextField(help_text='Customer-facing message shown for this status')),
            ],
        ),
    ]
