# Generated by Django 6.1 on 2026-08-24 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0003_statusnarration'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerparcel',
            name='customer_payment_status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid')], default='Unpaid', max_length=10),
        ),
    ]
