# Generated by Django 6.1 on 2026-08-25 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0004_customerparcel_customer_payment_status'),
        ('riders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerparcel',
            name='assigned_rider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_parcels', to='riders.rider'),
        ),
        migrations.AddField(
            model_name='customerparcel',
            name='tracking_qr_code',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='parcel_qr/'),
        ),
        migrations.AlterField(
            model_name='customerparcel',
            name='status',
            field=models.CharField(choices=[('Order', 'Order'), ('Ready to Pickup', 'Ready to Pickup'), ('Picked', 'Picked'), ('In Transit', 'In Transit'), ('Delivered', 'Delivered'), ('Parcel Not Available', 'Parcel Not Available'), ('Returned', 'Returned')], default='Order', max_length=30),
        ),
        migrations.AlterField(
            model_name='statusnarration',
            name='status',
            field=models.CharField(choices=[('Order', 'Order'), ('Ready to Pickup', 'Ready to Pickup'), ('Picked', 'Picked'), ('In Transit', 'In Transit'), ('Delivered', 'Delivered'), ('Parcel Not Available', 'Parcel Not Available'), ('Returned', 'Returned')], max_length=30, unique=True),
        ),
    ]
