# Generated by Django 6.1 on 2026-08-25 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0005_customerparcel_assigned_rider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerparcel',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
