# Generated by Django 6.1 on 2026-08-25 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0006_customerparcel_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerparcel',
            name='city',
            field=models.CharField(blank=True, choices=[('Karachi', 'Karachi'), ('Lahore', 'Lahore'), ('Islamabad', 'Islamabad'), ('Rawalpindi', 'Rawalpindi'), ('Faisalabad', 'Faisalabad'), ('Multan', 'Multan'), ('Peshawar', 'Peshawar'), ('Quetta', 'Quetta'), ('Sialkot', 'Sialkot'), ('Gujranwala', 'Gujranwala'), ('Hyderabad', 'Hyderabad'), ('Bahawalpur', 'Bahawalpur'), ('Sargodha', 'Sargodha'), ('Sukkur', 'Sukkur'), ('Larkana', 'Larkana'), ('Sheikhupura', 'Sheikhupura'), ('Rahim Yar Khan', 'Rahim Yar Khan'), ('Jhang', 'Jhang'), ('Gujrat', 'Gujrat'), ('Mardan', 'Mardan'), ('Kasur', 'Kasur'), ('Dera Ghazi Khan', 'Dera Ghazi Khan'), ('Sahiwal', 'Sahiwal'), ('Nawabshah', 'Nawabshah'), ('Mingora', 'Mingora'), ('Okara', 'Okara'), ('Mirpur Khas', 'Mirpur Khas'), ('Chiniot', 'Chiniot'), ('Kamoke', 'Kamoke'), ('Mandi Bahauddin', 'Mandi Bahauddin'), ('Jhelum', 'Jhelum'), ('Sadiqabad', 'Sadiqabad'), ('Jacobabad', 'Jacobabad'), ('Shikarpur', 'Shikarpur'), ('Khanewal', 'Khanewal'), ('Hafizabad', 'Hafizabad'), ('Kohat', 'Kohat'), ('Muzaffargarh', 'Muzaffargarh'), ('Khanpur', 'Khanpur'), ('Gojra', 'Gojra'), ('Mandi Bahauddin', 'Mandi Bahauddin'), ('Abbottabad', 'Abbottabad'), ('Turbat', 'Turbat'), ('Dadu', 'Dadu'), ('Bahawalnagar', 'Bahawalnagar'), ('Muridke', 'Muridke'), ('Pakpattan', 'Pakpattan'), ('Attock', 'Attock'), ('Vehari', 'Vehari'), ('Nowshera', 'Nowshera'), ('Chakwal', 'Chakwal'), ('Swabi', 'Swabi'), ('Dera Ismail Khan', 'Dera Ismail Khan'), ('Chishtian', 'Chishtian'), ('Daska', 'Daska'), ('Mansehra', 'Mansehra'), ('Nankana Sahib', 'Nankana Sahib'), ('Wah Cantt', 'Wah Cantt'), ('Kot Addu', 'Kot Addu'), ('Toba Tek Singh', 'Toba Tek Singh'), ('Ahmedpur East', 'Ahmedpur East'), ('Khairpur', 'Khairpur'), ('Chaman', 'Chaman'), ('Zhob', 'Zhob'), ('Gwadar', 'Gwadar'), ('Khuzdar', 'Khuzdar'), ('Muzaffarabad', 'Muzaffarabad'), ('Mirpur (AJK)', 'Mirpur (AJK)'), ('Gilgit', 'Gilgit'), ('Skardu', 'Skardu'), ('Charsadda', 'Charsadda'), ('Hangu', 'Hangu'), ('Ferozwala', 'Ferozwala'), ('Burewala', 'Burewala'), ('Jaranwala', 'Jaranwala'), ('Kabirwala', 'Kabirwala')], max_length=100, null=True),
        ),
    ]
