# Generated by Django 6.1 on 2026-08-28 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0007_alter_customerparcel_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerparcel',
            name='destination',
        ),
        migrations.AlterField(
            model_name='customerparcel',
            name='status',
            field=models.CharField(choices=[('Order', 'Order'), ('Ready for Pickup', 'Ready for Pickup'), ('Departed from Origin', 'Departed from Origin'), ('In Transit', 'In Transit'), ('Delivered', 'Delivered'), ('Parcel Not Available', 'Parcel Not Available'), ('Returned', 'Returned')], default='Order', max_length=30),
        ),
        migrations.AlterField(
            model_name='statusnarration',
            name='status',
            field=models.CharField(choices=[('Order', 'Order'), ('Ready for Pickup', 'Ready for Pickup'), ('Departed from Origin', 'Departed from Origin'), ('In Transit', 'In Transit'), ('Delivered', 'Delivered'), ('Parcel Not Available', 'Parcel Not Available'), ('Returned', 'Returned')], max_length=30, unique=True),
        ),
    ]
