# Generated by Django 6.1 on 2026-08-29 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0008_remove_customerparcel_destination_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerparcel',
            name='customer_loadsheet',
        ),
        migrations.RemoveField(
            model_name='customerparcel',
            name='loadsheet',
        ),
        migrations.AlterField(
            model_name='customerparcel',
            name='status',
            field=models.CharField(choices=[('Order', 'Order'), ('Ready for Pickup', 'Ready for Pickup'), ('Out for Delivery', 'Out for Delivery'), ('In Transit', 'In Transit'), ('Delivered', 'Delivered'), ('Parcel Not Available', 'Parcel Not Available'), ('Returned', 'Returned')], default='Order', max_length=30),
        ),
        migrations.AlterField(
            model_name='statusnarration',
            name='status',
            field=models.CharField(choices=[('Order', 'Order'), ('Ready for Pickup', 'Ready for Pickup'), ('Out for Delivery', 'Out for Delivery'), ('In Transit', 'In Transit'), ('Delivered', 'Delivered'), ('Parcel Not Available', 'Parcel Not Available'), ('Returned', 'Returned')], max_length=30, unique=True),
        ),
    ]
