# Generated by Django 6.1 on 2026-08-30 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0009_remove_customerparcel_customer_loadsheet_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StatusNarration',
        ),
        migrations.AlterField(
            model_name='customerparcel',
            name='status',
            field=models.CharField(choices=[('Order', 'Order'), ('Ready for Pickup', 'Ready for Pickup'), ('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered'), ('Parcel Not Available', 'Parcel Not Available'), ('Returned', 'Returned')], default='Order', max_length=30),
        ),
    ]
