# Generated by Django 6.1 on 2026-08-30 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0010_delete_statusnarration_alter_customerparcel_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerparcel',
            options={'permissions': [('can_scan_parcel_delivery', 'Can scan Parcel QR for delivery')]},
        ),
    ]
