# Generated by Django 6.1 on 2026-08-22 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('parcels', '0002_alter_customerparcel_api_sp_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loadsheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loadsheet_no', models.CharField(blank=True, editable=False, max_length=50)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('loadsheet_date', models.DateTimeField(auto_now_add=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='loadsheet_qr/')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loadsheets', to='customers.customer')),
                ('parcels', models.ManyToManyField(blank=True, related_name='loadsheets', to='parcels.customerparcel')),
            ],
        ),
    ]
