# Generated by Django 6.1 on 2026-08-19 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_display_name', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_city', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_branch', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_user', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_brand_name', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('customer_cnic', models.CharField(blank=True, max_length=20, null=True)),
                ('customer_phone_number', models.CharField(max_length=20)),
                ('customer_alternate_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('sales_person', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10)),
                ('return_details_show', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3)),
                ('show_billing_section', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=3)),
                ('show_balance', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=3)),
                ('show_dc', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=3)),
                ('customer_product_details', models.TextField(blank=True, null=True)),
                ('customer_address', models.TextField(blank=True, null=True)),
                ('customer_pickup_address', models.TextField(blank=True, null=True)),
                ('third_party_booking_auto', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3)),
                ('third_party_booking', models.CharField(blank=True, max_length=100, null=True)),
                ('third_party_booking_type', models.CharField(default='OVERNIGHT', max_length=50)),
                ('third_party_booking_by', models.CharField(default='Selected', max_length=50)),
                ('alternate_third_party_booking', models.CharField(blank=True, max_length=100, null=True)),
                ('alternate_third_party_booking_type', models.CharField(blank=True, max_length=100, null=True)),
                ('show_shipper_logo_in_label', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3)),
                ('shipper_allow_to_open', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3)),
                ('auto_update_pickup_status', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3)),
                ('show_third_party_label', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3)),
                ('live_tpl_tracking', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=3)),
                ('show_tpl_tracking_cn', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=3)),
                ('show_direct_tpl_status', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3)),
                ('select_courier_in_loadsheet', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3)),
                ('customer_prefix', models.CharField(blank=True, max_length=20, null=True)),
                ('shipper_brand_logo', models.ImageField(blank=True, null=True, upload_to='shipper_logos/')),
                ('default_intractions', models.CharField(blank=True, max_length=255, null=True)),
                ('api_key', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('weight_calculate', models.CharField(default='Full KG 1.0', max_length=50)),
                ('additional_calculate', models.CharField(default='Weight Same', max_length=50)),
                ('calculate_type', models.CharField(default='Unlimited Weights', max_length=50)),
                ('return_rate_apply', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=3)),
                ('limited_service_type', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3)),
                ('zone_type', models.CharField(default='Two Zone', max_length=50)),
                ('default_rate_template', models.CharField(blank=True, max_length=100, null=True)),
                ('default_tax_template', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_bank_title', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_bank_name', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_bank_ac', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_bank_ibn_number', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourierPickupList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courier', models.CharField(blank=True, max_length=100, null=True)),
                ('pickup_id', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courier_pickup_list', to='customers.customer')),
            ],
        ),
        migrations.CreateModel(
            name='RateTemplateEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(blank=True, max_length=100, null=True)),
                ('service_type', models.CharField(blank=True, max_length=100, null=True)),
                ('charge_type', models.CharField(blank=True, max_length=100, null=True)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('return_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_templates', to='customers.customer')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceTypeList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_type_list', to='customers.customer')),
            ],
        ),
        migrations.CreateModel(
            name='TaxTemplateEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(blank=True, max_length=100, null=True)),
                ('tax_type', models.CharField(blank=True, max_length=100, null=True)),
                ('formula_type', models.CharField(blank=True, max_length=100, null=True)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_templates', to='customers.customer')),
            ],
        ),
    ]
