# Generated by Django 6.1 on 2026-08-23 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
