# Generated by Django 6.1 on 2026-08-25 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rider',
            name='cnic_back_image',
            field=models.ImageField(default='', upload_to='rider_cnic/'),
        ),
        migrations.AddField(
            model_name='rider',
            name='cnic_front_image',
            field=models.ImageField(default='', upload_to='rider_cnic/'),
        ),
        migrations.AddField(
            model_name='rider',
            name='cnic_number',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='rider',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
    ]
