# Generated by Django 6.1 on 2026-08-29 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riders', '0002_rider_cnic_back_image_rider_cnic_front_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rider',
            name='vehicle_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
