# Generated by Django 6.1 on 2026-09-05 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riders', '0003_rider_vehicle_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='rider',
            name='vehicle_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
