# Generated by Django 6.1 on 2026-08-22 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('parcels', '0003_statusnarration'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliverySheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ds_number', models.CharField(blank=True, editable=False, max_length=50)),
                ('user', models.CharField(blank=True, max_length=100, null=True)),
                ('branch', models.CharField(blank=True, max_length=100, null=True)),
                ('rider', models.CharField(blank=True, max_length=100, null=True)),
                ('sheet_status', models.CharField(choices=[('Open', 'Open'), ('Close', 'Close')], default='Open', max_length=10)),
                ('origin', models.CharField(blank=True, max_length=100, null=True)),
                ('area', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('parcels', models.ManyToManyField(blank=True, related_name='delivery_sheets', to='parcels.customerparcel')),
            ],
        ),
        migrations.CreateModel(
            name='Manifest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, editable=False, max_length=50)),
                ('user', models.CharField(blank=True, max_length=100, null=True)),
                ('branch', models.CharField(blank=True, max_length=100, null=True)),
                ('origin', models.CharField(blank=True, max_length=100, null=True)),
                ('destination', models.CharField(blank=True, max_length=100, null=True)),
                ('mode_of_transportation', models.CharField(choices=[('By Road', 'By Road'), ('By Air', 'By Air')], default='By Road', max_length=20)),
                ('seal_no', models.CharField(blank=True, max_length=50, null=True)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('parcels', models.ManyToManyField(blank=True, related_name='manifests', to='parcels.customerparcel')),
            ],
        ),
        migrations.CreateModel(
            name='PickupSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_number', models.CharField(blank=True, editable=False, max_length=50)),
                ('rider', models.CharField(blank=True, max_length=100, null=True)),
                ('loadsheet', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.CharField(blank=True, max_length=100, null=True)),
                ('branch', models.CharField(blank=True, max_length=100, null=True)),
                ('pickup_status', models.CharField(choices=[('Uncomplete', 'Uncomplete'), ('Complete', 'Complete')], default='Uncomplete', max_length=15)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='pickup_qr/')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('parcels', models.ManyToManyField(blank=True, related_name='pickup_sheets', to='parcels.customerparcel')),
                ('shipper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_sheets', to='customers.customer')),
            ],
        ),
    ]
