# Generated by Django 6.1 on 2026-08-22 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickupsheet',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='pickupsheet',
            name='branch',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pickupsheet',
            name='qr_code',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='pickup_qr/'),
        ),
        migrations.AlterField(
            model_name='pickupsheet',
            name='user',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True),
        ),
    ]
