# Generated by Django 6.1 on 2026-08-25 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_customer_created_at'),
        ('operations', '0002_pickupsheet_last_update_alter_pickupsheet_branch_and_more'),
        ('riders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickupsheet',
            name='rider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickup_sheets', to='riders.rider'),
        ),
        migrations.AlterField(
            model_name='pickupsheet',
            name='shipper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pickup_sheets', to='customers.customer'),
        ),
    ]
