# Generated by Django 6.1 on 2026-08-25 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_alter_pickupsheet_rider_alter_pickupsheet_shipper'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pickupsheet',
            name='loadsheet',
        ),
    ]
