# Generated by Django 6.1 on 2026-08-29 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_customer_created_at'),
        ('operations', '0004_remove_pickupsheet_loadsheet'),
        ('riders', '0003_rider_vehicle_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverysheet',
            name='area',
        ),
        migrations.RemoveField(
            model_name='deliverysheet',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='deliverysheet',
            name='origin',
        ),
        migrations.RemoveField(
            model_name='deliverysheet',
            name='user',
        ),
        migrations.AddField(
            model_name='deliverysheet',
            name='pickup_sheet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_sheets', to='operations.pickupsheet'),
        ),
        migrations.AddField(
            model_name='deliverysheet',
            name='qr_code',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='delivery_qr/'),
        ),
        migrations.AddField(
            model_name='deliverysheet',
            name='scanned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliverysheet',
            name='shipper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_sheets', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='deliverysheet',
            name='tracking_number',
            field=models.CharField(blank=True, editable=False, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='deliverysheet',
            name='ds_number',
            field=models.CharField(blank=True, editable=False, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='deliverysheet',
            name='rider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_sheets', to='riders.rider'),
        ),
        migrations.AlterField(
            model_name='deliverysheet',
            name='sheet_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Picked Up', 'Picked Up'), ('Cancelled', 'Cancelled')], default='Pending', max_length=10),
        ),
    ]
