# Generated by Django 6.1 on 2026-08-30 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_customer_created_at'),
        ('operations', '0005_remove_deliverysheet_area_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='deliverysheet',
            unique_together={('pickup_sheet', 'shipper')},
        ),
    ]
