# Generated by Django 6.1 on 2026-08-30 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0006_alter_deliverysheet_unique_together'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Manifest',
        ),
    ]
