# Generated by Django 6.1 on 2026-08-30 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0007_delete_manifest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliverysheet',
            options={'permissions': [('can_scan_delivery_sheet', 'Can scan Delivery Sheet QR')]},
        ),
    ]
