# Generated by Django 6.1 on 2026-08-22 21:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='city_name',
        ),
        migrations.AddField(
            model_name='destination',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destinations', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='destination',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destination',
            name='location',
            field=models.CharField(blank=True, help_text='Latitude,Longitude', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='name',
            field=models.CharField(default='Unnamed', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destination',
            name='short_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='zone',
            field=models.CharField(blank=True, choices=[('With in City', 'With in City'), ('Different', 'Different'), ('Same', 'Same')], max_length=20, null=True),
        ),
    ]
