# Generated by Django 6.1 on 2026-08-22 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_remove_destination_city_name_destination_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='city',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='customer',
        ),
    ]
