# Generated by Django 6.1 on 2026-08-22 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_remove_branch_city_remove_destination_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='zone',
            field=models.CharField(blank=True, choices=[('With in City', 'With in City'), ('Different', 'Different'), ('Same', 'Same'), ('Zone 1', 'Zone 1'), ('Zone 2', 'Zone 2'), ('Zone 3', 'Zone 3'), ('Zone 4', 'Zone 4'), ('Zone 5', 'Zone 5'), ('Zone 6', 'Zone 6'), ('Zone 7', 'Zone 7')], max_length=20, null=True),
        ),
    ]
