# Generated by Django 6.1 on 2026-08-22 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_alter_destination_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
