# Generated by Django 6.1 on 2026-08-31 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_destination_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Destination',
        ),
    ]
