"""
Django settings for payparcel project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""
from django.templatetags.static import static
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
from decouple import config
import dj_database_url

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-temporary-key-for-dev')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = ['127.0.0.1', 'localhost', '.onrender.com']


# Application definition

INSTALLED_APPS = [
    'unfold',
    'unfold.contrib.filters',
    'cloudinary_storage',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'cloudinary',
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'django_unfold_admin_listfilter_dropdown',
    'rangefilter',
    'customers',
    'locations',
    'parcels',
    'invoices',
    'operations',
    'riders'
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'payparcel.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'payparcel.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        default=config('DATABASE_URL', default='sqlite:///db.sqlite3'),
        conn_max_age=600
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Karachi'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

STORAGES = {
    'default': {
        'BACKEND': 'cloudinary_storage.storage.MediaCloudinaryStorage',
    },
    'staticfiles': {
        'BACKEND': 'payparcel.storage.SilentCollectstaticStorage',
    },
}
STATICFILES_STORAGE = 'payparcel.storage.SilentCollectstaticStorage'

MEDIA_URL = '/media/'

# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}

CORS_ALLOWED_ORIGINS = [
    "https://your-bolt-app-url.vercel.app",  # we'll update this once Bolt is deployed too
]
CORS_ALLOW_ALL_ORIGINS = True  # temporary for testing, we'll restrict this later
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    )
}

UNFOLD = {
    "SITE_TITLE": "PayParcel Admin",
    "SITE_HEADER": "PayParcel",
    "SITE_URL": "/",
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": True,
    "BORDER_RADIUS": "8px",
    "SCRIPTS": [
    lambda request: static("admin/js/unfold_overrides.js"),
    ],
    "STYLES": [
        lambda request: static("admin/css/unfold_overrides.css"),
    ],
    "COLORS": {
        "primary": {
            "50": "239 246 255",
            "100": "219 234 254",
            "200": "191 219 254",
            "300": "147 197 253",
            "400": "96 165 250",
            "500": "29 78 216",
            "600": "37 99 235",
            "700": "29 78 216",
            "800": "30 64 175",
            "900": "30 58 138",
            "950": "23 37 84",
        },
    },
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": False,
        "navigation": [
            {
                "title": _(""),
                "separator": False,
                "items": [
                    {
                        "title": _("Dashboard"),
                        "icon": "dashboard",
                        "link": reverse_lazy("admin:index"),
                    },
                ],
            },

            {
                "title":"",
                "separator": True,
                "collapsible": False,
                "items": [
                    {"title": _("Customers"), "icon": "person", "link": reverse_lazy("admin:customers_customer_changelist"), "permission": lambda r: r.user.has_perm('customers.view_customer')},
                    {"title": _("Customer parcels"), "icon": "inventory_2", "link": reverse_lazy("admin:parcels_customerparcel_changelist"), "permission": lambda r: r.user.has_perm('parcels.view_customerparcel')},
                    {"title": _("Pickup sheets"), "icon": "local_shipping", "link": reverse_lazy("admin:operations_pickupsheet_changelist"), "permission": lambda r: r.user.has_perm('operations.view_pickupsheet')},
                    {"title": _("Delivery sheets"), "icon": "task", "link": reverse_lazy("admin:operations_deliverysheet_changelist"), "permission": lambda r: r.user.has_perm('operations.view_deliverysheet')},
                    {"title": _("Invoices"), "icon": "receipt_long", "link": reverse_lazy("admin:invoices_invoice_changelist"), "permission": lambda r: r.user.has_perm('invoices.view_invoice')},
                    {"title": _("Branchs"), "icon": "store", "link": reverse_lazy("admin:locations_branch_changelist"), "permission": lambda r: r.user.has_perm('locations.view_branch')},
                ],
            },

            {
                "title": _("People & Permissions"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {"title": _("Riders"), "icon": "two_wheeler", "link": reverse_lazy("admin:riders_rider_changelist"), "permission": lambda r: r.user.has_perm('riders.view_rider')},
                    {"title": _("Users"), "icon": "manage_accounts", "link": reverse_lazy("admin:auth_user_changelist"), "permission": lambda r: r.user.is_superuser},
                    {"title": _("Groups"), "icon": "shield_person", "link": reverse_lazy("admin:auth_group_changelist"), "permission": lambda r: r.user.is_superuser},
                ],
            },
        ],
    },
}

CLOUDINARY_STORAGE = {
    'CLOUD_NAME': config('CLOUDINARY_CLOUD_NAME'),
    'API_KEY': config('CLOUDINARY_API_KEY'),
    'API_SECRET': config('CLOUDINARY_API_SECRET'),
}

SITE_BASE_URL = config('SITE_BASE_URL', default='https://payparcel-backend.onrender.com')

MASTER_ADMIN_USERNAME = config('MASTER_ADMIN_USERNAME', default='')